---
- name: Install nginx for redhat os
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_facts['os_family'] | lower == 'redhat'

- name: Install nginx for ubuntu os
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] | lower == 'ubuntu'