- name: Create user accounts
  user:
    name: team
    password: '$6$vpaN7aGcq6L$NBnjoOcXZUJzK/qI34wb1ii.S1VZqzGSu7AylZLjRaLOEeU/04oWjVYG85Y3pUFvi1CSFMSMMvEl9LdNlSHzt.'
    groups: docker
    append: yes
    state: present
    shell: /bin/bash
    system: no
    create_home: yes
    home: /home/team

