- name: Create user accounts
  ansible.builtin.user:
    name: team
    password: '$6$vpaN7aGcq6L$NBnjoOcXZUJzK/qI34wb1ii.S1VZqzGSu7AylZLjRaLOEeU/04oWjVYG85Y3pUFvi1CSFMSMMvEl9LdNlSHzt.'
    groups: docker, sudo
    append: yes
    state: present
    shell: /bin/bash
    system: no
    create_home: yes
    home: /home/team

- name: Create ssh directories
  ansible.builtin.file:
    path: "/home/team/.ssh"
    state: directory
    owner: team
    group: team
    mode: '0700'

- name: Create authorized_keys file
  ansible.builtin.file:
    path: "/home/team/.ssh/authorized_keys"
    state: touch
    owner: team
    group: team
    mode: '0644'

# - name: Exec command to reboot server
#   reboot:
#     msg: Reboot inicialized by Ansible
#     reboot_timeout: 200

# - name: Ping servers
#   ansible.builtin.ping: