- name: Delete directory
  ansible.builtin.file:
    path: "/home/team/tasks"
    state: absent

- name: Copy directory from main server
  ansible.builtin.copy:
    src: "/home/ivanh/tasks"
    dest: "/home/team/"
