- name: Generate ssh keys
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: "icmr_cluster/.ssh_teams/{{ item }}"
    force: no
  loop: "{{ teams }}"