- name: Install iptables rules
  import_playbook: ../iptables_install/install.yml

- name: Install docker
  import_playbook: ../docker_install/install.yml

- name: Create users
  import_playbook: ../users_install/install.yml

- name: Install monitoring
  import_playbook: ../monitoring_install/install.yml

- hosts: all
  become: true
  tasks:
    - name: Exec command to reboot server
      reboot:
        msg: Reboot inicialized by Ansible
        reboot_timeout: 200

    - name: Ping servers
      ansible.builtin.ping: